### ISSUE TITLE
Too long number animation duration

### ISSUE THREAD

**Issue by preet-dabre** [wearevasai/covid-19#1]
## Problem
The `data-number` used for **Active Cases** , **Deceased**, etc takes too long to load (_specifically: **7000 ms**_)

## Proposed Solution
Please change the duration **from 7000 ms to less than 3000 ms**, which is sent to `jQuery.animateNumber()` in your `counter()` method.

Also show **Total Cases** (active + deceased + recovered) as opposed to just **Active Cases** as followed by [worldometers](https://www.worldometers.info/coronavirus/), [covid19india](https://www.covid19india.org/), etc.

##
PS: Great job w/ the website

Regards, P

**Comment by wearevasai** [comment]
Thank you for your feedback Preet, we will work on getting the counter animation duration resolved, for the sake of time, we just picked up a template that suited and populated the data that we had collated. We will be adding more funcitionality in due course.
